import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Navbar from "@/components/tutorial/navbar";


export const metadata: Metadata = {
  title: "Gomlla - جـمـلـة سهلتها عليك و سهلتها على عميلك",
  description: "Generated by create next app",
};

import { CartProvider } from "@/hooks/use-cart";

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`rubik-700 antialiased bg-background w-full mx-auto transition-all duration-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          enableColorScheme={true}
          storageKey="theme"
          disableTransitionOnChange
        >
          <CartProvider>
            <section className="w-full justify-center items-center flex flex-col">
              <Navbar />
              {children}
            </section>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
