import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Navbar from "@/components/tutorial/navbar";
import Header from "@/components/tutorial/Header";


export const metadata: Metadata = {
  title: "Gomlla - جـمـلـة سهلتها عليك و سهلتها على عميلك",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`rubik-700 antialiased bg-background max-w-[1440px] mx-auto transition-all duration-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          enableColorScheme={true}
          storageKey="theme"
          disableTransitionOnChange
        >
          <section className="w-full justify-center items-center flex flex-col">
            <Navbar />
            {children}
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
